vim.keymap.set('n', 's', 'cl') -- for some reason this got mapped to nop?
vim.keymap.set('n', '<Up>', '<C-w>k')
vim.keymap.set('n', '<Down>', '<C-w>j')
vim.keymap.set('n', '<Left>', '<C-w>h')
vim.keymap.set('n', '<Right>', '<C-w>l')
vim.keymap.set('n', '<Ctrl>/', 'Vgc')
vim.keymap.set('n', '<leader>,', '^w<')
vim.keymap.set('n', '<leader>.', '^w>')
vim.keymap.set('n', '<leader>gg', ':Neogit kind=floating<CR>')
-- vim.keymap.set('n', '<leader>pu', ':Git push<CR>')
vim.keymap.set('n', '<leader>oc', ':e %:h<CR>', { desc = '[O]pen [C]urrent directory' })
vim.keymap.set('n', '<leader>bx', ':%bd|e#|bd#<CR>', { desc = 'Delete [b]uffers e[x]cept current' })
vim.keymap.set('n', '<leader>ng', require('neogen').generate, { desc = '[N]eo[G]en' })
vim.keymap.set('n', '<leader>ad', ':!ansible-vault decrypt %<CR><CR>', { desc = '[A]nsible [D]ecrypt' })
vim.keymap.set('n', '<leader>ae', ':!ansible-vault encrypt --encrypt-vault-id default %<CR><CR>', { desc = '[A]nsible [E]ncrypt' })
vim.keymap.set('n', '<leader>gD', vim.lsp.buf.declaration, { desc = '[G]oto [D]eclaration' })
vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename, { desc = '[R]e[N]ame' })
local telescope = require 'telescope.builtin'
vim.keymap.set('n', 'gd', telescope.lsp_definitions, { desc = '[G]oto [D]efinition' })
vim.keymap.set('n', 'gr', telescope.lsp_references, { desc = '[G]oto [R]eferences' })
vim.keymap.set('n', 'ff', telescope.find_files, { desc = 'Telescope [F]ind [F]iles' })
vim.keymap.set('n', '<leader>gf', telescope.git_files, { desc = 'Telescope [G]it [F]iles' })
vim.keymap.set('n', '<leader>fg', telescope.live_grep, { desc = 'Telescope [F]ind with [G]rep' })
vim.keymap.set('n', '<leader> ', telescope.buffers, { desc = '[F]ind open [B]uffers' })
vim.keymap.set('n', '<leader>sh', telescope.help_tags, { desc = '[S]earch [H]elp' })
vim.keymap.set('n', '<leader>sd', telescope.diagnostics, { desc = '[S]earch [D]iagnostics' })
